name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop
  
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Run Test coverage
        run: go test -coverprofile=coverage.out